import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { TRPCReactProvider } from "@/trpc/react";
import SolanaWalletProvider from "@/app/_providers/solana.provider";
import { Navigation } from "./_components/Navigation";

export const metadata: Metadata = {
  title: "bFlow",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} h-full`}>
      <body className="h-full overflow-hidden">
        <TRPCReactProvider>
          <SolanaWalletProvider>
            <Navigation />
            <main className="h-[calc(100%-4rem)] overflow-hidden">
              {children}
            </main>
          </SolanaWalletProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
